# .pre-commit-config.yaml

default_language_version:
    python: python3.13

repos:
  # 1. RUFF RODA PRIMEIRO para linting e correções automáticas.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1 
    hooks:
      # Hook para o linter. A opção --fix tenta corrigir os erros.
      - id: ruff-check
        name: ruff (linter)
        args: [--fix]
      # Hook para o formatador do próprio Ruff (alternativa ao Black).
      # Podemos manter desativado por enquanto para usar o Black.
      # - id: ruff-format
      #   name: ruff (formatter)

  # 2. ISORT RODA EM SEGUIDA para organizar os imports.
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1 
    hooks:
      - id: isort
        name: isort (organização de imports)

  # 3. BLACK RODA POR ÚLTIMO para garantir a formatação final.
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        name: black (formatação de código)