# .github/workflows/ci.yml
name: CI - Teste e Qualidade do Código

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Fazer checkout do código
        uses: actions/checkout@v5

      - name: 2. Configurar Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: 3. Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: 4. Instalar dependências com Poetry
        run: poetry install --no-interaction

      - name: 5. Verificar formatação e lint com Ruff, Black e isort
        run: |
          poetry run ruff check .
          poetry run black --check .
          poetry run isort --check .

      - name: 6. Rodar testes e gerar dados de cobertura
        run: |
          poetry run coverage run --source=autodub -m pytest
          poetry run coverage report -m
          poetry run coverage xml -i

      - name: 7. Enviar relatório de cobertura para o Coveralls
        uses: coverallsapp/github-action@v2
        with:
          # Usamos o formato Cobertura e o arquivo gerado coverage.xml
          format: cobertura
          file: coverage.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          # Se seu repo é privado ou você prefere usar token do Coveralls, defina o secret
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN || '' }}
