# .github/workflows/ci.yml
name: CI - Teste e Qualidade do Código

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Fazer checkout do código
        uses: actions/checkout@v5

      - name: 2. Configurar Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: 3. Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: 4. Cache Poetry e pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: 5. Instalar dependências com Poetry
        run: poetry install --no-interaction

      - name: 6. Verificar formatação e lint com Ruff, Black e isort
        run: |
          poetry run ruff check .
          poetry run black --check .
          poetry run isort --check .

      - name: 7. Rodar testes e gerar dados de cobertura
        run: |
          poetry run coverage run --source=autodub -m pytest
          poetry run coverage report -m
          poetry run coverage xml -i

      - name: 8. Verificar limite mínimo de cobertura
        run: |
          # falhará se cobertura < 100%
          poetry run coverage report -m --fail-under=100

      - name: 9. Enviar relatório de cobertura para o Coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: cobertura
          file: coverage.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN || '' }}
